#!/usr/bin/env bash

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"

# Shortcuts
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias p="cd ~/projects"

# Git aliases
if [ -x "$(command -v git)" ]; then
    alias g="git"
    alias gca="git commit -a -m "
fi


# use exa instead of ls if available for colored output
if [ -x "$(command -v exa)" ]; then
    alias ls="exa --all"
    alias la="exa --long --all --group"
fi

# use bat instead of cat if it exists

if [ -x "$(command -v bat)" ]; then
    alias cat="bat"
fi
if [ -x "$(command -v lfscroll)" ]; then
    alias lf="lfscroll"
fi

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Enable aliases to be sudo’ed
# alias sudo='sudo '


# IP addresses
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ip r | grep default"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"
